 export const GirlsProducts = [
  {
    id: 1,
    name: 'Girls Tutu Dress',
    category: 'girls',
    subCategory: 'dresses',
    price: 1299,
    oldPrice: 1799,
    rating: 4.8,
    reviews: 108,
    badge: 'Popular',
    colors: ['Pink', 'Purple', 'White'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500&h=600&fit=crop',
    description: 'Adorable layered tutu dress — perfect for birthdays and parties.',
  },
  {
    id: 2,
    name: 'Girls Denim Overalls',
    category: 'girls',
    subCategory: 'overalls',
    price: 1499,
    oldPrice: 1999,
    rating: 4.7,
    reviews: 78,
    badge: 'Popular',
    colors: ['Blue', 'Light Blue'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=500&h=600&fit=crop',
    description: 'Classic denim overalls with adjustable straps — durable and adorable.',
  },
  {
    id: 3,
    name: 'Girls Floral Frock',
    category: 'girls',
    subCategory: 'dresses',
    price: 1199,
    oldPrice: 1699,
    rating: 4.9,
    reviews: 164,
    badge: 'New',
    colors: ['Yellow', 'Pink', 'Sky Blue'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500&h=600&fit=crop',
    description: 'Flowy floral frock with ruffled sleeves — a springtime favourite.',
  },
  {
    id: 4,
    name: 'Girls Cotton Top',
    category: 'girls',
    subCategory: 'tops',
    price: 699,
    oldPrice: 999,
    rating: 4.5,
    reviews: 92,
    badge: 'Sale',
    colors: ['White', 'Pink', 'Mint'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=500&h=600&fit=crop',
    description: 'Soft cotton top with a cute bow detail — ideal for everyday wear.',
  },
  {
    id: 5,
    name: 'Girls Leggings Pack',
    category: 'girls',
    subCategory: 'bottoms',
    price: 799,
    oldPrice: 1099,
    rating: 4.6,
    reviews: 201,
    badge: 'Popular',
    colors: ['Black', 'Navy', 'Pink'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&h=600&fit=crop',
    description: 'Pack of 3 stretchy leggings — comfy, colourful, and everyday-ready.',
  },
  {
    id: 6,
    name: 'Girls Party Gown',
    category: 'girls',
    subCategory: 'dresses',
    price: 2499,
    oldPrice: 3299,
    rating: 5.0,
    reviews: 87,
    badge: 'New',
    colors: ['Red', 'Purple', 'Gold'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&h=600&fit=crop',
    description: 'Elegant party gown with satin finish — perfect for special occasions.',
  },
  {
    id: 7,
    name: 'Girls Knit Cardigan',
    category: 'girls',
    subCategory: 'sweaters',
    price: 1099,
    oldPrice: 1499,
    rating: 4.7,
    reviews: 112,
    badge: 'Sale',
    colors: ['Cream', 'Pink', 'Lavender'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&h=600&fit=crop',
    description: 'Cozy knit cardigan with buttons — a sweet layer for cooler days.',
  },
  {
    id: 8,
    name: 'Girls Ballet Flats',
    category: 'girls',
    subCategory: 'footwear',
    price: 1199,
    oldPrice: 1599,
    rating: 4.6,
    reviews: 134,
    badge: 'Popular',
    colors: ['Pink', 'White', 'Black'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&h=600&fit=crop',
    description: 'Classic ballet flats with a soft bow — comfortable and elegant.',
  },
  {
    id: 9,
    name: 'Girls Hair Accessory Set',
    category: 'girls',
    subCategory: 'accessories',
    price: 499,
    oldPrice: 699,
    rating: 4.8,
    reviews: 156,
    badge: 'Sale',
    colors: ['Multicolor'],
    sizes: ['One Size'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&h=600&fit=crop',
    description: 'Set of 10 hair clips and bands — bright, fun, and gentle on hair.',
  },
  {
    id: 10,
    name: 'Girls Denim Skirt',
    category: 'girls',
    subCategory: 'skirts',
    price: 999,
    oldPrice: 1399,
    rating: 4.5,
    reviews: 88,
    badge: 'New',
    colors: ['Blue', 'Light Blue', 'Black'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&h=600&fit=crop',
    description: 'Denim skirt with an elastic waist — cute, casual, and easy to style.',
  },
];

export default GirlsProducts;