 export const KidsProducts = [
  {
    id: 1,
    name: 'Kids Dinosaur Hoodie',
    category: 'kids',
    subCategory: 'hoodies',
    price: 899,
    oldPrice: 1299,
    rating: 4.7,
    reviews: 142,
    badge: 'Sale',
    colors: ['Green', 'Blue', 'Grey'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=500&h=600&fit=crop',
    description: 'Fun dinosaur-print hoodie made from ultra-soft cotton for kids.',
  },
  {
    id: 2,
    name: 'Kids Striped Sweatshirt',
    category: 'kids',
    subCategory: 'sweatshirts',
    price: 999,
    oldPrice: 1399,
    rating: 4.5,
    reviews: 96,
    badge: 'Sale',
    colors: ['Navy', 'Red', 'Grey'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=500&h=600&fit=crop',
    description: 'Comfy striped sweatshirt for kids — soft, warm, and easy to wash.',
  },
  {
    id: 3,
    name: 'Kids Denim Jacket',
    category: 'kids',
    subCategory: 'jackets',
    price: 1499,
    oldPrice: 1999,
    rating: 4.6,
    reviews: 84,
    badge: 'New',
    colors: ['Blue', 'Light Blue'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=500&h=600&fit=crop',
    description: 'Adorable mini denim jacket — a stylish layer for cooler days.',
  },
  {
    id: 4,
    name: 'Kids Cotton T-Shirt Pack',
    category: 'kids',
    subCategory: 'tshirts',
    price: 799,
    oldPrice: 1099,
    rating: 4.8,
    reviews: 213,
    badge: 'Popular',
    colors: ['White', 'Blue', 'Yellow'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500&h=600&fit=crop',
    description: 'Pack of 3 soft cotton tees — everyday comfort for active kids.',
  },
  {
    id: 5,
    name: 'Kids Jogger Pants',
    category: 'kids',
    subCategory: 'pants',
    price: 899,
    oldPrice: 1199,
    rating: 4.5,
    reviews: 118,
    badge: 'Sale',
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&h=600&fit=crop',
    description: 'Stretchy jogger pants with an elastic waist — perfect for playtime.',
  },
  {
    id: 6,
    name: 'Kids Puffer Jacket',
    category: 'kids',
    subCategory: 'jackets',
    price: 2199,
    oldPrice: 2899,
    rating: 4.9,
    reviews: 156,
    badge: 'New',
    colors: ['Red', 'Navy', 'Black'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=600&fit=crop',
    description: 'Warm puffer jacket with a cozy hood — ideal for winter adventures.',
  },
  {
    id: 7,
    name: 'Kids Cartoon Pajama Set',
    category: 'kids',
    subCategory: 'sleepwear',
    price: 699,
    oldPrice: 999,
    rating: 4.7,
    reviews: 189,
    badge: 'Popular',
    colors: ['Blue', 'Pink', 'Green'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1533514114760-4384f1e4b8d0?w=500&h=600&fit=crop',
    description: 'Fun cartoon-print pajama set — soft, breathable, and bedtime-approved.',
  },
  {
    id: 8,
    name: 'Kids Sneakers',
    category: 'kids',
    subCategory: 'footwear',
    price: 1299,
    oldPrice: 1699,
    rating: 4.6,
    reviews: 142,
    badge: 'Sale',
    colors: ['White', 'Black', 'Blue'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: false,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&h=600&fit=crop',
    description: 'Lightweight kids sneakers with cushioned soles for all-day comfort.',
  },
  {
    id: 9,
    name: 'Kids Raincoat',
    category: 'kids',
    subCategory: 'outerwear',
    price: 1099,
    oldPrice: 1499,
    rating: 4.5,
    reviews: 76,
    badge: 'New',
    colors: ['Yellow', 'Blue', 'Red'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=500&h=600&fit=crop',
    description: 'Waterproof raincoat with a playful design — keeps little ones dry and happy.',
  },
  {
    id: 10,
    name: 'Kids Beanie Hat',
    category: 'kids',
    subCategory: 'accessories',
    price: 399,
    oldPrice: 599,
    rating: 4.8,
    reviews: 102,
    badge: 'Sale',
    colors: ['Red', 'Grey', 'Green'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=500&h=600&fit=crop',
    description: 'Soft knit beanie to keep little heads warm all winter long.',
  },
];

export default KidsProducts;