export const MensProducts = [
  {
    id: 1,
    name: 'Classic Denim Jacket',
    category: 'mens',
    subCategory: 'jackets',
    price: 2499,
    oldPrice: 3499,
    rating: 4.8,
    reviews: 124,
    badge: 'Sale',
    colors: ['Blue', 'Black', 'Light Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&h=600&fit=crop',
    description: 'Timeless denim jacket with a modern fit. Perfect for layering all year round.',
  },
  {
    id: 2,
    name: 'Oversized Linen Shirt',
    category: 'mens',
    subCategory: 'shirts',
    price: 1299,
    oldPrice: 1899,
    rating: 4.6,
    reviews: 89,
    badge: 'New',
    colors: ['White', 'Beige', 'Sky Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=600&fit=crop',
    description: 'Breathable oversized linen shirt — a summer wardrobe essential.',
  },
  {
    id: 3,
    name: 'Slim Fit Chino Pants',
    category: 'mens',
    subCategory: 'pants',
    price: 1799,
    oldPrice: 2299,
    rating: 4.5,
    reviews: 156,
    badge: 'Sale',
    colors: ['Khaki', 'Navy', 'Olive'],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&h=600&fit=crop',
    description: 'Slim fit chinos made from premium stretch cotton for all-day comfort.',
  },
  {
    id: 4,
    name: 'Leather Biker Jacket',
    category: 'mens',
    subCategory: 'jackets',
    price: 4999,
    oldPrice: 6999,
    rating: 4.9,
    reviews: 187,
    badge: 'Popular',
    colors: ['Black', 'Brown'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=600&fit=crop',
    description: 'Edgy leather biker jacket with premium hardware and a tailored fit.',
  },
  {
    id: 5,
    name: 'Men’s Graphic Tee',
    category: 'mens',
    subCategory: 'tshirts',
    price: 799,
    oldPrice: 1099,
    rating: 4.3,
    reviews: 231,
    badge: 'Sale',
    colors: ['Black', 'White', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=600&fit=crop',
    description: 'Everyday graphic tee with a relaxed fit and durable print.',
  },
  {
    id: 6,
    name: 'Men’s Puffer Vest',
    category: 'mens',
    subCategory: 'vests',
    price: 2199,
    oldPrice: 2899,
    rating: 4.4,
    reviews: 65,
    badge: 'Sale',
    colors: ['Black', 'Navy', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: false,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=600&fit=crop',
    description: 'Lightweight puffer vest — ideal for layering in transitional weather.',
  },
  {
    id: 7,
    name: 'Men’s Oxford Shirt',
    category: 'mens',
    subCategory: 'shirts',
    price: 1499,
    oldPrice: 1999,
    rating: 4.7,
    reviews: 178,
    badge: 'Popular',
    colors: ['White', 'Light Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&h=600&fit=crop',
    description: 'Classic oxford shirt with a crisp finish — a wardrobe must-have.',
  },
  {
    id: 8,
    name: 'Men’s Cargo Joggers',
    category: 'mens',
    subCategory: 'pants',
    price: 1599,
    oldPrice: 2099,
    rating: 4.5,
    reviews: 143,
    badge: 'New',
    colors: ['Black', 'Olive', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=500&h=600&fit=crop',
    description: 'Relaxed cargo joggers with multiple pockets — comfort meets utility.',
  },
  {
    id: 9,
    name: 'Men’s Wool Overcoat',
    category: 'mens',
    subCategory: 'coats',
    price: 5999,
    oldPrice: 7999,
    rating: 4.9,
    reviews: 97,
    badge: 'Popular',
    colors: ['Charcoal', 'Camel', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&h=600&fit=crop',
    description: 'Tailored wool overcoat that elevates any winter outfit.',
  },
  {
    id: 10,
    name: 'Men’s Bomber Jacket',
    category: 'mens',
    subCategory: 'jackets',
    price: 3299,
    oldPrice: 4299,
    rating: 4.6,
    reviews: 156,
    badge: 'New',
    colors: ['Black', 'Olive', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=600&fit=crop',
    description: 'Sleek bomber jacket with ribbed cuffs — casual yet refined.',
  },
  {
    id: 11,
    name: 'Men’s Polo T-Shirt',
    category: 'mens',
    subCategory: 'tshirts',
    price: 999,
    oldPrice: 1399,
    rating: 4.4,
    reviews: 204,
    badge: 'Sale',
    colors: ['Navy', 'White', 'Maroon'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500&h=600&fit=crop',
    description: 'Smart-casual polo tee made from breathable pique cotton.',
  },
  {
    id: 12,
    name: 'Men’s Hooded Sweatshirt',
    category: 'mens',
    subCategory: 'hoodies',
    price: 1699,
    oldPrice: 2199,
    rating: 4.7,
    reviews: 189,
    badge: 'Popular',
    colors: ['Grey', 'Black', 'Maroon'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&h=600&fit=crop',
    description: 'Cozy hooded sweatshirt with a kangaroo pocket and soft fleece lining.',
  },
  {
    id: 13,
    name: 'Men’s Formal Blazer',
    category: 'mens',
    subCategory: 'blazers',
    price: 4499,
    oldPrice: 5999,
    rating: 4.8,
    reviews: 112,
    badge: 'New',
    colors: ['Black', 'Navy', 'Charcoal'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=600&fit=crop',
    description: 'Sharp formal blazer with structured shoulders — perfect for events.',
  },
  {
    id: 14,
    name: 'Men’s Track Pants',
    category: 'mens',
    subCategory: 'pants',
    price: 1199,
    oldPrice: 1599,
    rating: 4.5,
    reviews: 167,
    badge: 'Sale',
    colors: ['Black', 'Navy', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500&h=600&fit=crop',
    description: 'Athletic track pants with tapered fit and moisture-wicking fabric.',
  },
  {
    id: 15,
    name: 'Men’s Leather Belt',
    category: 'mens',
    subCategory: 'accessories',
    price: 899,
    oldPrice: 1299,
    rating: 4.6,
    reviews: 218,
    badge: 'Popular',
    colors: ['Brown', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=600&fit=crop',
    description: 'Genuine leather belt with a brushed metal buckle — a timeless accessory.',
  },
];
export default MensProducts;