export const WomensProducts = [
  {
    id: 1,
    name: 'Floral Summer Dress',
    category: 'womens',
    subCategory: 'dresses',
    price: 2199,
    oldPrice: 2999,
    rating: 4.9,
    reviews: 210,
    badge: 'Popular',
    colors: ['Pink', 'Yellow', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&h=600&fit=crop',
    description: 'Flowy floral dress with a flattering silhouette — perfect for sunny days.',
  },
  {
    id: 2,
    name: 'Knit Turtleneck Sweater',
    category: 'womens',
    subCategory: 'sweaters',
    price: 1899,
    oldPrice: 2499,
    rating: 4.7,
    reviews: 98,
    badge: 'New',
    colors: ['Cream', 'Charcoal', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&h=600&fit=crop',
    description: 'Cozy knit turtleneck sweater — soft, warm, and effortlessly stylish.',
  },
  {
    id: 3,
    name: 'High-Waist Midi Skirt',
    category: 'womens',
    subCategory: 'skirts',
    price: 1599,
    oldPrice: 2099,
    rating: 4.4,
    reviews: 73,
    badge: 'Sale',
    colors: ['Beige', 'Black', 'Emerald'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&h=600&fit=crop',
    description: 'Pleated high-waist midi skirt with a fluid drape and elegant movement.',
  },
  {
    id: 4,
    name: 'Silk Evening Gown',
    category: 'womens',
    subCategory: 'dresses',
    price: 5999,
    oldPrice: 7999,
    rating: 5.0,
    reviews: 64,
    badge: 'New',
    colors: ['Navy', 'Champagne', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&h=600&fit=crop',
    description: 'Luxurious silk evening gown — a timeless statement for special occasions.',
  },
  {
    id: 5,
    name: 'Women’s Crop Blazer',
    category: 'womens',
    subCategory: 'blazers',
    price: 2799,
    oldPrice: 3699,
    rating: 4.6,
    reviews: 87,
    badge: 'New',
    colors: ['Beige', 'Black', 'White'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500&h=600&fit=crop',
    description: 'Structured crop blazer that transitions from office to evening.',
  },
  {
    id: 6,
    name: 'Ribbed Bodycon Dress',
    category: 'womens',
    subCategory: 'dresses',
    price: 1699,
    oldPrice: 2299,
    rating: 4.7,
    reviews: 143,
    badge: 'Sale',
    colors: ['Black', 'Rust', 'Olive'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=600&fit=crop',
    description: 'Sleek ribbed bodycon dress — stretchy, flattering, and party-ready.',
  },
  {
    id: 7,
    name: 'Women’s Linen Blouse',
    category: 'womens',
    subCategory: 'tops',
    price: 1399,
    oldPrice: 1899,
    rating: 4.5,
    reviews: 121,
    badge: 'Popular',
    colors: ['White', 'Sand', 'Sky Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=600&fit=crop',
    description: 'Breezy linen blouse with a relaxed fit — ideal for warm days.',
  },
  {
    id: 8,
    name: 'Women’s Wide-Leg Trousers',
    category: 'womens',
    subCategory: 'pants',
    price: 2099,
    oldPrice: 2699,
    rating: 4.6,
    reviews: 102,
    badge: 'Popular',
    colors: ['Beige', 'Black', 'Camel'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=500&h=600&fit=crop',
    description: 'Elegant wide-leg trousers with a tailored drape — smart and comfortable.',
  },
  {
    id: 9,
    name: 'Women’s Denim Jacket',
    category: 'womens',
    subCategory: 'jackets',
    price: 2299,
    oldPrice: 2999,
    rating: 4.8,
    reviews: 167,
    badge: 'Popular',
    colors: ['Blue', 'Light Blue', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&h=600&fit=crop',
    description: 'Classic denim jacket with a cropped fit — layers over everything.',
  },
  {
    id: 10,
    name: 'Women’s Wrap Midi Dress',
    category: 'womens',
    subCategory: 'dresses',
    price: 1999,
    oldPrice: 2699,
    rating: 4.7,
    reviews: 138,
    badge: 'Sale',
    colors: ['Emerald', 'Navy', 'Maroon'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=600&fit=crop',
    description: 'Flattering wrap midi dress with a tie waist — perfect for any occasion.',
  },
  {
    id: 11,
    name: 'Women’s Cable Knit Cardigan',
    category: 'womens',
    subCategory: 'sweaters',
    price: 2199,
    oldPrice: 2899,
    rating: 4.6,
    reviews: 94,
    badge: 'New',
    colors: ['Cream', 'Grey', 'Dusty Pink'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&h=600&fit=crop',
    description: 'Chunky cable knit cardigan — cozy, layer-friendly, and timeless.',
  },
  {
    id: 12,
    name: 'Women’s Satin Slip Dress',
    category: 'womens',
    subCategory: 'dresses',
    price: 2499,
    oldPrice: 3299,
    rating: 4.9,
    reviews: 156,
    badge: 'Popular',
    colors: ['Champagne', 'Black', 'Emerald'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&h=600&fit=crop',
    description: 'Silky satin slip dress — effortlessly elegant for day or night.',
  },
  {
    id: 13,
    name: 'Women’s Pleated Skirt',
    category: 'womens',
    subCategory: 'skirts',
    price: 1499,
    oldPrice: 1999,
    rating: 4.5,
    reviews: 89,
    badge: 'Sale',
    colors: ['Navy', 'Beige', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&h=600&fit=crop',
    description: 'A-line pleated skirt with a soft shimmer — dress up or down.',
  },
  {
    id: 14,
    name: 'Women’s Leather Handbag',
    category: 'womens',
    subCategory: 'accessories',
    price: 3499,
    oldPrice: 4499,
    rating: 4.8,
    reviews: 201,
    badge: 'Popular',
    colors: ['Tan', 'Black', 'Burgundy'],
    sizes: ['One Size'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=600&fit=crop',
    description: 'Structured leather handbag with gold-tone hardware — a daily staple.',
  },
  {
    id: 15,
    name: 'Women’s Ankle Boots',
    category: 'womens',
    subCategory: 'footwear',
    price: 2999,
    oldPrice: 3999,
    rating: 4.7,
    reviews: 178,
    badge: 'New',
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=600&fit=crop',
    description: 'Chic ankle boots with a block heel — walk confidently all day.',
  },
];

export default WomensProducts;