// data/products.js

export const products = [
  // ==================== MENS ====================
  {
    id: 1,
    name: 'Classic Denim Jacket',
    category: 'mens',
    subCategory: 'jackets',
    price: 2499,
    oldPrice: 3499,
    rating: 4.8,
    reviews: 124,
    badge: 'Sale',
    colors: ['Blue', 'Black', 'Light Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&h=600&fit=crop',
    description: 'Timeless denim jacket with a modern fit. Perfect for layering all year round.',
  },
  {
    id: 2,
    name: 'Cotton Oversized Tee',
    category: 'mens',
    subCategory: 't-shirts',
    price: 799,
    oldPrice: 1199,
    rating: 4.6,
    reviews: 89,
    badge: 'New',
    colors: ['White', 'Black', 'Grey', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=600&fit=crop',
    description: 'Soft 100% cotton oversized tee. Breathable and effortlessly stylish.',
  },
  {
    id: 3,
    name: 'Slim Fit Chinos',
    category: 'mens',
    subCategory: 'pants',
    price: 1599,
    oldPrice: 2199,
    rating: 4.7,
    reviews: 156,
    badge: 'Sale',
    colors: ['Beige', 'Olive', 'Navy', 'Black'],
    sizes: ['30', '32', '34', '36', '38'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&h=600&fit=crop',
    description: 'Tailored slim-fit chinos with stretch for all-day comfort.',
  },
  {
    id: 4,
    name: 'Leather Ankle Boots',
    category: 'mens',
    subCategory: 'footwear',
    price: 3999,
    oldPrice: 5499,
    rating: 4.9,
    reviews: 203,
    badge: 'Hot',
    colors: ['Brown', 'Black'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=500&h=600&fit=crop',
    description: 'Premium leather boots with durable soles and classic styling.',
  },
  {
    id: 5,
    name: 'Formal White Shirt',
    category: 'mens',
    subCategory: 'shirts',
    price: 1299,
    oldPrice: 1799,
    rating: 4.5,
    reviews: 78,
    badge: null,
    colors: ['White', 'Light Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=600&fit=crop',
    description: 'Crisp formal shirt with wrinkle-resistant fabric. Office-ready.',
  },
  {
    id: 6,
    name: 'Wool Blend Overcoat',
    category: 'mens',
    subCategory: 'jackets',
    price: 5999,
    oldPrice: 7999,
    rating: 4.8,
    reviews: 92,
    badge: 'Sale',
    colors: ['Charcoal', 'Camel', 'Navy'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=500&h=600&fit=crop',
    description: 'Sophisticated wool-blend overcoat for premium warmth and style.',
  },

  // ==================== WOMENS ====================
  {
    id: 7,
    name: 'Floral Summer Dress',
    category: 'womens',
    subCategory: 'dresses',
    price: 1899,
    oldPrice: 2699,
    rating: 4.9,
    reviews: 234,
    badge: 'Hot',
    colors: ['Floral Pink', 'Floral Blue', 'Floral Yellow'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&h=600&fit=crop',
    description: 'Flowy floral dress perfect for summer brunches and vacations.',
  },
  {
    id: 8,
    name: 'Pleated Midi Skirt',
    category: 'womens',
    subCategory: 'skirts',
    price: 1499,
    oldPrice: 1999,
    rating: 4.7,
    reviews: 67,
    badge: 'New',
    colors: ['Black', 'Beige', 'Emerald'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&h=600&fit=crop',
    description: 'Elegant pleated midi skirt that transitions from day to night.',
  },
  {
    id: 9,
    name: 'Silk Blouse',
    category: 'womens',
    subCategory: 'tops',
    price: 2199,
    oldPrice: 2999,
    rating: 4.8,
    reviews: 145,
    badge: 'Sale',
    colors: ['Ivory', 'Blush Pink', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1564257577617-4b0d0a6b6c7c?w=500&h=600&fit=crop',
    description: 'Luxurious silk blouse with a relaxed drape. Effortlessly chic.',
  },
  {
    id: 10,
    name: 'High-Waist Skinny Jeans',
    category: 'womens',
    subCategory: 'jeans',
    price: 1799,
    oldPrice: 2499,
    rating: 4.6,
    reviews: 312,
    badge: 'Sale',
    colors: ['Dark Blue', 'Light Blue', 'Black'],
    sizes: ['24', '26', '28', '30', '32'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&h=600&fit=crop',
    description: 'Figure-flattering high-waist jeans with premium stretch denim.',
  },
  {
    id: 11,
    name: 'Wool Knit Sweater',
    category: 'womens',
    subCategory: 'sweaters',
    price: 1999,
    oldPrice: 2799,
    rating: 4.7,
    reviews: 98,
    badge: null,
    colors: ['Cream', 'Rust', 'Forest Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=500&h=600&fit=crop',
    description: 'Cozy wool sweater with a relaxed fit. Your new winter staple.',
  },
  {
    id: 12,
    name: 'Leather Handbag',
    category: 'womens',
    subCategory: 'accessories',
    price: 3499,
    oldPrice: 4999,
    rating: 4.9,
    reviews: 189,
    badge: 'Hot',
    colors: ['Tan', 'Black', 'Burgundy'],
    sizes: ['One Size'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=600&fit=crop',
    description: 'Handcrafted leather handbag with multiple compartments.',
  },

  // ==================== GIRLS ====================
  {
    id: 13,
    name: 'Floral Party Frock',
    category: 'girls',
    subCategory: 'dresses',
    price: 1299,
    oldPrice: 1799,
    rating: 4.8,
    reviews: 76,
    badge: 'New',
    colors: ['Pink', 'Purple', 'Yellow'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=500&h=600&fit=crop',
    description: 'Adorable floral frock for birthday parties and special occasions.',
  },
  {
    id: 14,
    name: 'Denim Dungaree',
    category: 'girls',
    subCategory: 'dungarees',
    price: 999,
    oldPrice: 1499,
    rating: 4.6,
    reviews: 54,
    badge: 'Sale',
    colors: ['Blue', 'Light Blue'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&h=600&fit=crop',
    description: 'Cute and comfy denim dungaree. Perfect for playtime.',
  },
  {
    id: 15,
    name: 'Cotton T-Shirt Pack (3)',
    category: 'girls',
    subCategory: 't-shirts',
    price: 799,
    oldPrice: 1199,
    rating: 4.7,
    reviews: 121,
    badge: 'Sale',
    colors: ['Pink/White/Yellow', 'Blue/Green/Purple'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=500&h=600&fit=crop',
    description: 'Pack of 3 soft cotton tees in fun colors. Great value.',
  },
  {
    id: 16,
    name: 'Ballet Flats',
    category: 'girls',
    subCategory: 'footwear',
    price: 899,
    oldPrice: 1299,
    rating: 4.5,
    reviews: 43,
    badge: null,
    colors: ['Pink', 'White', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=500&h=600&fit=crop',
    description: 'Classic ballet flats with cushioned insoles for all-day comfort.',
  },
  {
    id: 17,
    name: 'Hair Accessories Set',
    category: 'girls',
    subCategory: 'accessories',
    price: 499,
    oldPrice: 799,
    rating: 4.8,
    reviews: 88,
    badge: 'Hot',
    colors: ['Multicolor'],
    sizes: ['One Size'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&h=600&fit=crop',
    description: 'Complete hair accessory set with bows, clips, and bands.',
  },

  // ==================== KIDS ====================
  {
    id: 18,
    name: 'Cartoon Print T-Shirt',
    category: 'kids',
    subCategory: 't-shirts',
    price: 599,
    oldPrice: 899,
    rating: 4.7,
    reviews: 156,
    badge: 'Sale',
    colors: ['Blue', 'Red', 'Green'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=500&h=600&fit=crop',
    description: 'Fun cartoon-print tee made from soft, kid-friendly cotton.',
  },
  {
    id: 19,
    name: 'Kids Jogger Pants',
    category: 'kids',
    subCategory: 'pants',
    price: 899,
    oldPrice: 1299,
    rating: 4.6,
    reviews: 92,
    badge: null,
    colors: ['Grey', 'Navy', 'Black'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=500&h=600&fit=crop',
    description: 'Comfy jogger pants with elastic waist. Ideal for play and school.',
  },
  {
    id: 20,
    name: 'Winter Puffer Jacket',
    category: 'kids',
    subCategory: 'jackets',
    price: 1999,
    oldPrice: 2999,
    rating: 4.9,
    reviews: 145,
    badge: 'Sale',
    colors: ['Red', 'Blue', 'Yellow'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500&h=600&fit=crop',
    description: 'Warm puffer jacket with water-resistant shell. Snow-day ready.',
  },
  {
    id: 21,
    name: 'School Uniform Shirt',
    category: 'kids',
    subCategory: 'shirts',
    price: 699,
    oldPrice: 999,
    rating: 4.5,
    reviews: 67,
    badge: null,
    colors: ['White', 'Light Blue'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1604004555489-723a93d6ce74?w=500&h=600&fit=crop',
    description: 'Durable school uniform shirt with stain-resistant finish.',
  },
  {
    id: 22,
    name: 'Sneakers',
    category: 'kids',
    subCategory: 'footwear',
    price: 1199,
    oldPrice: 1699,
    rating: 4.8,
    reviews: 210,
    badge: 'Hot',
    colors: ['White', 'Blue', 'Pink'],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&h=600&fit=crop',
    description: 'Lightweight sneakers with velcro straps. Easy on, easy off.',
  },
  {
    id: 23,
    name: 'Cartoon Pajama Set',
    category: 'kids',
    subCategory: 'nightwear',
    price: 799,
    oldPrice: 1199,
    rating: 4.7,
    reviews: 134,
    badge: 'New',
    colors: ['Blue', 'Pink', 'Yellow'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500&h=600&fit=crop',
    description: 'Soft cotton pajama set with fun cartoon prints. Sweet dreams!',
  },
];

// Optional: Export categories separately for easy filtering
export const categoryList = [
  { name: 'All', slug: 'all', count: products.length },
  { name: 'Mens', slug: 'mens', count: products.filter((p) => p.category === 'mens').length },
  { name: 'Womens', slug: 'womens', count: products.filter((p) => p.category === 'womens').length },
  { name: 'Girls', slug: 'girls', count: products.filter((p) => p.category === 'girls').length },
  { name: 'Kids', slug: 'kids', count: products.filter((p) => p.category === 'kids').length },
];

export default products;